name: Typst CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: 'curl -s https://api.github.com/repos/typst/typst/releases/latest | grep "browser_download_url.*typst-x86_64-unknown-linux-musl.tar.xz" | cut -d : -f 2,3 | tr -d \" | wget -qi -'
      - run: "tar -xf typst-x86_64-unknown-linux-musl.tar.xz"
      - run: "typst-x86_64-unknown-linux-musl/typst compile main.typ"
      - uses: actions/upload-artifact@v2
        with:
          path: |
            main.pdf
